// Code to toggle between tabs
// function openCity(cityName) {
//   var i;
//   var x = document.getElementsByClassName("city");
//   for (i = 0; i < x.length; i++) {
//     x[i].style.display = "none";
//   }
//   document.getElementById(cityName).style.display = "block";
// }

// Task will be generated by Js
